language: python
python:
  - '3.5'
  - '3.6'
  - '3.7'
matrix:
  include:
    - python: 3.8
      dist: focal
install:
    - python setup.py install
    - pip install -r requirements-dev.txt
script: pytest tests/
